Improving search
tuzig/terminal7 pull request #237
Opened 2022-06-26 11:09 UTC by eyal-sasson

2022-06-26 15:40 UTC, daonb requested changes
Just a bit of cosmetics

2022-06-26 15:40 UTC, daonb commented on css/terminal7.css
> +    background-color: #3e3446;
better to use vars for color values. check the top of the file for an example.

2022-06-26 15:40 UTC, daonb commented on src/pane.js
> +        } else {
no need to add `{` in 306 and `}` here

2022-06-26 15:40 UTC, daonb commented on src/pane.js
> +
blank line

2022-06-26 15:40 UTC, daonb commented on src/pane.js
> +            }
no need for `{}`

2022-06-30 19:48 UTC, daonb commented on css/terminal7.css
> +    background-color: #3e3446;
I've played with the color and I think it's best to go with what we have in the site - #11051E

2022-06-30 19:51 UTC, daonb commented
I really like the look of the search box and would love to merge this.

Anything I can do to help?

2022-07-01 10:12 UTC, eyal-sasson commented
> I really like the look of the search box and would love to merge this.
> 
> Anything I can do to help?

Not anything I can think of, thanks.
I'll probably finish working on this on Sunday.

2022-07-03 15:40 UTC, daonb requested changes
Found two more color constants

2022-07-03 15:40 UTC, daonb commented on css/terminal7.css
> +    background: #01fafa;
Make it var

2022-07-03 15:40 UTC, daonb commented on css/terminal7.css
> +    background: #3e3446;
make it a var

2022-07-06 04:29 UTC, merged