Refactoring connection user flow
tuzig/terminal7 pull request #261
Opened 2022-08-07 10:48 UTC by eyal-sasson

Closes #233.
WIP: WebRTC flow is done, still need to add SSH.

2022-08-22 11:32 UTC, eyal-sasson commented
Also closes #259 now.

2022-08-23 10:18 UTC, daonb requested changes

2022-08-23 10:18 UTC, daonb commented on src/terminal7.js
> +            this.pb.close()
Please add `this.pb = null` after the close

2022-08-23 10:18 UTC, daonb commented on tests/gate.test.js
> +        // g.tryWebexec = false
remove commented code

2022-08-24 07:13 UTC, eyal-sasson commented on src/gate.ts
> +			w = new Window({name:name, gate: this, id: id})
It is a const, there's a comma above

2022-08-25 13:40 UTC, daonb requested changes
Almost there...

2022-08-25 13:40 UTC, daonb commented on src/form.ts
> +			Form.disposeCurrent = () => {
Please remove a duplication of 63:68

2022-08-25 13:40 UTC, daonb commented on src/form.ts
> +	static disposeCurrent: () => void
This is a "constant" function , better defined it the typescript way. Also, we need a better name, so please change to:

```typescript
// closes the active form 
static close() {
   ...
}
```

2022-08-25 13:40 UTC, daonb commented on src/form.ts
> +                        else if (key.length == 1) {
What are we ignoring? please add a comment on the line before

2022-08-25 13:40 UTC, daonb commented on src/gate.ts
> +            this.onConnected = this.load
Add a comment before:

```typescript
// first onConnected is special if it's a new gate but once connected, we're back to load

2022-08-25 13:40 UTC, daonb commented on index.html
> +		  <nav>
This came out pretty ugly. please remove the X button

2022-09-01 04:48 UTC, merged